# -*- coding: utf-8 -*-
"""Proyecto Final v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xb0mXsYJZEF2CMkSLRR-xuqpZkK1texy
"""

##cartelera principal
cartelera = {
    "Lunes": [
        {"pelicula": "Resident Evil: Noche Cero", "sala": 1, "horario": "2:00 pm", "formato": "Normal"},
        {"pelicula": "Avengers: Endgame (reestreno)", "sala": 2, "horario": "4:30 pm", "formato": "3D"},
        {"pelicula": "Los Juegos del Hambre: Sinsajo Pt. 2", "sala": 3, "horario": "6:00 pm", "formato": "4DX"},
        {"pelicula": "Rápido y Furioso (reestreno)", "sala": 4, "horario": "5:30 pm", "formato": "Normal"},
        {"pelicula": "El Final", "sala": 5, "horario": "8:00 pm", "formato": "CXC"},
    ],
    "Martes": [
        {"pelicula": "Resident Evil: Noche Cero", "sala": 3, "horario": "5:00 pm", "formato": "4DX"},
        {"pelicula": "Avengers: Endgame (reestreno)", "sala": 1, "horario": "7:00 pm", "formato": "Normal"},
        {"pelicula": "Los Juegos del Hambre: Sinsajo Pt. 2", "sala": 2, "horario": "3:00 pm", "formato": "Normal"},
        {"pelicula": "Rápido y Furioso (reestreno)", "sala": 5, "horario": "6:30 pm", "formato": "3D"},
        {"pelicula": "El Final", "sala": 4, "horario": "9:00 pm", "formato": "Normal"},
    ],
    "Miércoles": [
        {"pelicula": "Resident Evil: Noche Cero", "sala": 4, "horario": "4:00 pm", "formato": "Normal"},
        {"pelicula": "Avengers: Endgame (reestreno)", "sala": 5, "horario": "2:30 pm", "formato": "CXC"},
        {"pelicula": "Los Juegos del Hambre: Sinsajo Pt. 2", "sala": 1, "horario": "7:30 pm", "formato": "3D"},
        {"pelicula": "Rápido y Furioso (reestreno)", "sala": 2, "horario": "5:00 pm", "formato": "Normal"},
        {"pelicula": "El Final", "sala": 3, "horario": "8:30 pm", "formato": "4DX"},
    ],
    "Jueves": [
        {"pelicula": "Resident Evil: Noche Cero", "sala": 2, "horario": "6:30 pm", "formato": "3D"},
        {"pelicula": "Avengers: Endgame (reestreno)", "sala": 3, "horario": "3:30 pm", "formato": "Normal"},
        {"pelicula": "Los Juegos del Hambre: Sinsajo Pt. 2", "sala": 4, "horario": "8:00 pm", "formato": "Normal"},
        {"pelicula": "Rápido y Furioso (reestreno)", "sala": 1, "horario": "2:00 pm", "formato": "4DX"},
        {"pelicula": "El Final", "sala": 5, "horario": "5:30 pm", "formato": "CXC"},
    ],
    "Viernes": [
        {"pelicula": "Resident Evil: Noche Cero", "sala": 5, "horario": "4:00 pm", "formato": "Normal"},
        {"pelicula": "Avengers: Endgame (reestreno)", "sala": 4, "horario": "7:00 pm", "formato": "3D"},
        {"pelicula": "Los Juegos del Hambre: Sinsajo Pt. 2", "sala": 1, "horario": "5:30 pm", "formato": "CXC"},
        {"pelicula": "Rápido y Furioso (reestreno)", "sala": 3, "horario": "9:00 pm", "formato": "Normal"},
        {"pelicula": "El Final", "sala": 2, "horario": "2:30 pm", "formato": "4DX"},
    ],
    "Sábado": [
        {"pelicula": "Resident Evil: Noche Cero", "sala": 1, "horario": "3:00 pm", "formato": "Normal"},
        {"pelicula": "Avengers: Endgame (reestreno)", "sala": 2, "horario": "6:00 pm", "formato": "4DX"},
        {"pelicula": "Los Juegos del Hambre: Sinsajo Pt. 2", "sala": 5, "horario": "8:30 pm", "formato": "3D"},
        {"pelicula": "Rápido y Furioso (reestreno)", "sala": 4, "horario": "4:30 pm", "formato": "Normal"},
        {"pelicula": "El Final", "sala": 3, "horario": "7:30 pm", "formato": "CXC"},
    ],
    "Domingo": [
        {"pelicula": "Resident Evil: Noche Cero", "sala": 3, "horario": "2:30 pm", "formato": "3D"},
        {"pelicula": "Avengers: Endgame (reestreno)", "sala": 5, "horario": "5:00 pm", "formato": "Normal"},
        {"pelicula": "Los Juegos del Hambre: Sinsajo Pt. 2", "sala": 2, "horario": "7:00 pm", "formato": "CXC"},
        {"pelicula": "Rápido y Furioso (reestreno)", "sala": 1, "horario": "8:30 pm", "formato": "4DX"},
        {"pelicula": "El Final", "sala": 4, "horario": "4:00 pm", "formato": "Normal"},
    ],
}

## cambio de numero a dia de semana para acceder al diccionario por su clave *********************
def dia_semana(x):
    match x:
        case 1:
            x = 'Lunes'
            return x
        case 2:
            x = 'Martes'
            return x
        case 3:
            x = 'Miércoles'
            return x
        case 4:
            x = 'Jueves'
            return x
        case 5:
            x = 'Viernes'
            return x
        case 6:
            x = 'Sábado'
            return x
        case 7:
            x = 'Domingo'
            return x

##creacion de asientos para las pelis en los diccionarios*********************
for dia in cartelera:
     for sala in range(5):
         cartelera[dia][sala]['asientos'] = {
    'a': ["."] *6,
    'b': ["."] *6,
    'c': ["."] *6,
    'd': ["."] *6,
    'e': ["."] *6,
}

##variables inicializadas para usar luego, quizas...  *********************
dia = ''
pelicula = ''
sala = ''
horario = ''
formato = ''
dia_sem = ''
seleccion = ''

##funcion para mostrar asientos *********************
def mostrar_asientos():
  global dia_sem
  global seleccion
  if dia_sem == '':
      for ind,dia in enumerate(cartelera, start = 1):
                print(ind,'-',dia)
      dia_sem = int(input("Seleccione el día: "))
      dia_sem = dia_semana(dia_sem)
  else:
      dia_sem = dia_sem

  print(f"\nPara el dia {dia_sem} se encuentran las siguientes películas: \n")
  for ind,items in enumerate(cartelera[dia_sem], start = 1):
      print(ind,'- Pelicula:',items["pelicula"], '- Sala:',items["sala"],'- Horario:',items["horario"])

  seleccion = int(input("\nSeleccione la Pelicula que desea ver: "))
  seleccion = seleccion - 1

  print("\nAsientos disponibles para la pelicula seleccionada \n")
  print('- Pelicula:',cartelera[dia_sem][seleccion]["pelicula"], "sala", cartelera[dia_sem][seleccion]["sala"], "horario", cartelera[dia_sem][seleccion]["horario"])

  #print(cartelera[dia_sem][seleccion]["asientos"])
  print("\n      [PANTALLA]")
  print("_________________________")
  print("  1 | 2 | 3 | 4 | 5 | 6")
  for x,seat in cartelera[dia_sem][seleccion]["asientos"].items():
      print(x, " | ".join(seat))



##funcion para seleccionar asiento*********************
def seleccion_asiento():
  global seleccion
  nombre = input("\nIngrese su nombre: ")
  while True:
    try:
      fila = input("\nSeleccione la fila (Letra): ")
      fila = fila.lower()
      asiento = int(input("seleccione el numero de asiento: "))
      asiento = asiento - 1

      if cartelera[dia_sem][seleccion]["asientos"][fila][asiento] == 'X':
        print("Asiento ocupado, favor seleccionar otro asiento")
      else:
        cartelera[dia_sem][seleccion]["asientos"][fila][asiento] = 'X'
        print(f'\n Resumen de Orden\nNombre: {nombre}')
        print(f'Pelicula: {cartelera[dia_sem][seleccion]["pelicula"]}')
        print(f'Sala: {cartelera[dia_sem][seleccion]["sala"]}')
        print(f'Horario: {dia_sem} {cartelera[dia_sem][seleccion]["horario"]}')
        print(f'Formato: {cartelera[dia_sem][seleccion]["formato"]}')
        print(f"Asiento seleccionado: {fila.upper()}{asiento + 1}")
        break

    except:
      print("Opción no válida, favor reintentar\n")

#para seleccionar dia  *********************

def seleccion_dia_semana():
    global dia_sem
    try:
      for ind,dia in enumerate(cartelera, start = 1):
          print(ind,'-',dia)
      dia_sem = int(input("\nSeleccione el día: "))
      dia_sem = dia_semana(dia_sem)
    except:
      print("\nOpción no válida, favor reintentar\n")

#para mostrar cartelera *********************
def ver_cartelera():
    global dia_sem
    print(dia_sem)
    for ind,items in enumerate(cartelera[dia_sem], start = 1):
        print(ind,'- Pelicula:',items["pelicula"], '- Sala:',items["sala"], '- Horario:',items["horario"], '- Formato:',items["formato"])

#-----------

menu = """\n
===== CINEMAX - SISTEMA DE RESERVAS =====
1. Ver cartelera de un día
2. Mostrar asientos de una función
3. Reservar asiento
4. Cancelar reserva
5. Ver disponibilidad
6. Salir
"""

menu1 = ''

while menu1 != 6:
  try:
    dia_sem = ''
    print(menu)
    menu1 = int(input("\nSeleccione la opción a tomar: "))
    match(menu1):
        case 1: #cartelera *********************
          try:
            print("=== VER CARTELERA ===")
            seleccion_dia_semana()
            ver_cartelera()
            while True:
                print("Menu Secundario:")
                print("\n 1. Volver al menu principal")
                print(" 2. Cambiar de día")
                print(" 3. Mostrar asientos")
                seleccion2 = int(input("\nSeleccione la opción a tomar: "))
                if seleccion2 == 1:
                    ''
                    break
                elif seleccion2 == 2:
                    seleccion_dia_semana()
                    ver_cartelera()
                elif seleccion2 == 3:
                    mostrar_asientos()
          except:
            print("\nOpción no válida, favor reintentar")

        case 2: #ver asientos *********************
            print("=== MOSTRAR ASIENTOS ===")
            mostrar_asientos()

        case 3: #seleccionar asiento *********************
            print("=== SELECCIONAR ASIENTO ===")
            mostrar_asientos()
            seleccion_asiento()

        case 4: #cancelar reserva *********************
            print("=== CANCELAR RESERVA ===")
            try:

                seleccion_dia_semana()
                #print(dia_sem)
                sala = int(input("\nIngresa numero de sala: "))
                fila = input("Ingresa fila donde se encuentra tu asiento (letra): ").lower()
                asiento = int(input("Ingresa numero de asiento: "))
                asiento = asiento - 1


                for num,sel in enumerate(cartelera[dia_sem]):
                  if sel['sala'] == sala:
                    seleccion = num
                    if cartelera[dia_sem][seleccion]["asientos"][fila][asiento] == '.':
                      print("\nEl asiento seleccionado no tiene ninguna reserva, favor reintentar")
                    else:
                      cartelera[dia_sem][seleccion]["asientos"][fila][asiento] = '.'
                      print(f'\nPelicula: {cartelera[dia_sem][seleccion]["pelicula"]}')
                      print(f'Sala: {cartelera[dia_sem][seleccion]["sala"]}')
                      print(f'Horario: {dia_sem} {cartelera[dia_sem][seleccion]["horario"]}')
                      print(f'Formato: {cartelera[dia_sem][seleccion]["formato"]}')
                      print(f"Asiento seleccionado: {fila}{asiento + 1}")
                      print("***RESERVA CANCELADA***")

            except:
              print("\nLa reserva ingresada no fue encontrada, favor reintentar")


            #print(cartelera[dia_sem][seleccion]["asientos"])
        case 5: #para contabilizar disponibilidad *********************
          while True:
            print("=== VER DISPONIBILIDAD ===")
            print("\n1. Ver disponibilidad de una sala en específico\n2. Ver disponibilidad general de las funciones de un día\n3. Volver al menú principal")



            seleccion5 = int(input("\nSeleccione la opción a tomar: "))
            if seleccion5 == 1:
                qnt_disponible = 0
                qnt_ocupado = 0
                seleccion_dia_semana()
                ver_cartelera()
                seleccion = int(input("\nSeleccione la película a consultar disponibilidad: "))
                seleccion = seleccion - 1
                for letra in cartelera[dia_sem][seleccion]["asientos"]:
                    for valor in cartelera[dia_sem][seleccion]["asientos"][letra]:
                        if valor == '.':
                            qnt_disponible += 1
                        elif valor == 'X':
                            qnt_ocupado += 1
                print(f"    Pelicula: {cartelera[dia_sem][seleccion]["pelicula"]}, horario: {dia_sem}, {cartelera[dia_sem][seleccion]["horario"]}")
                print(f"    Asientos disponibles: {qnt_disponible}")
                print(f"    Asientos ocupados: {qnt_ocupado}")
                print(f"    Porcentaje de ocupación: {(qnt_ocupado/(qnt_disponible + qnt_ocupado))*100}%\n")


            elif seleccion5 == 2:
                seleccion_dia_semana()
                print(dia_sem)

                for ind,items in enumerate(cartelera[dia_sem]):
                  qnt_disponible = 0
                  qnt_ocupado = 0
                  print('- Pelicula:',items["pelicula"], '- Sala:',items["sala"], '- Horario:',items["horario"], '- Formato:',items["formato"])
                  for letra in cartelera[dia_sem][ind]["asientos"]:
                    for valor in cartelera[dia_sem][ind]["asientos"][letra]:
                        if valor == '.':
                            qnt_disponible += 1
                        elif valor == 'X':
                            qnt_ocupado += 1
                  print(f"    Asientos disponibles: {qnt_disponible}")
                  print(f"    Asientos ocupados: {qnt_ocupado}")
                  print(f"    Porcentaje de ocupación: {(qnt_ocupado/(qnt_disponible + qnt_ocupado))*100}%\n")


            elif seleccion5 == 3:
                ''
                break
            else:
                print("Opción no válida, favor reintentar")

        case 6:
            print('Saliendo...')
            break
        case _:
            print("Opción Inválida")

  except:
    print("Opción no válida, favor reintentar\n")

